# Generated by Django 4.0.3 on 2022-04-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
