# Generated by Django 4.0.3 on 2022-04-26 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyerapp', '0003_cart_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyerapp.buy')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyerapp.user')),
            ],
        ),
    ]
